//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LCCARBONELL;Initial Catalog=DBTAREO;Persist Security Info=True;User I" +
            "D=sa;Password=sistemas")]
        public string DBTAREOConnectionString {
            get {
                return ((string)(this["DBTAREOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SSK-ESQL01\\SSK_PRUEBAS01;Initial Catalog=DB_OPERACIONES;Persist Secur" +
            "ity Info=True;User ID=usrcare;Password=usrcare")]
        public string ConexionCGO {
            get {
                return ((string)(this["ConexionCGO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ssk-appdev;Initial Catalog=DBTAREO_OBRA;User ID=sa;Password=sistemas")]
        public string Conexion {
            get {
                return ((string)(this["Conexion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LCCARBONELL01\\LOCAL;Initial Catalog=DBTAREO;Persist Security Info=Tru" +
            "e;User ID=sa;Password=sistemas;MultipleActiveResultSets=True")]
        public string ConexionLocal {
            get {
                return ((string)(this["ConexionLocal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LCCARBONELL01;Initial Catalog=DBTAREO;User ID=sa;Password=sistemas")]
        public string DBTAREOConnectionString1 {
            get {
                return ((string)(this["DBTAREOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SSK-ESQL01\\SSK_PRUEBAS01;Initial Catalog=DBTAREO_OBRA;User ID=usrcare" +
            "")]
        public string DBTAREO_OBRAConnectionString {
            get {
                return ((string)(this["DBTAREO_OBRAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SSK-APPPRE;Initial Catalog=Aquarius;Persist Security Info=True;User I" +
            "D=sa;Password=SYSSA$1")]
        public string AquariusConnectionString {
            get {
                return ((string)(this["AquariusConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=DBTAREO_OBRA;Persist Security Info=True;User ID=sa" +
            ";Password=sistemas")]
        public string DBTAREO_OBRAConnectionString1 {
            get {
                return ((string)(this["DBTAREO_OBRAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HVB2P9O;Initial Catalog=DBTAREO_OBRA;User ID=sa;Password=sist" +
            "emas")]
        public string DBTAREO_OBRAConnectionString2 {
            get {
                return ((string)(this["DBTAREO_OBRAConnectionString2"]));
            }
        }
    }
}
